---
batch_size: 4
bucket_boundaries: [1, 2, 4, 8, 16, 32, 64, 128, 256]
num_epochs: 1
shuffle_buffer_size: 1000
learning_rate: 0.02
learning_first_decay_steps: 100
learning_t_mul: 2.0
learning_m_mul: 0.9
learning_alpha: 0.01
momentum: 0.9
embedding_size: 300
num_encoder_layers: 2
num_encoder_attention_heads: 4
num_encoder_attention_head_dims: 50
num_encoder_dense_dims: 600
num_decoder_layers: 2
num_decoder_attention_heads: 4
encoder_dense_activation: "tf.nn.leaky_relu"
encoder_dropout_rate: 0.1
save_checkpoints_mins: 20
log_device_placement: false
beam_size: 5
keep_checkpoint_max: 5
